import QtQuick

ListModel{
    id:modelaccount
    ListElement{
        src:"/Resrc/logo/7.png"
        account:"零钱"
    }
    ListElement{
        src:"/Resrc/logo/7.png"
        account:"零钱通"
    }
    ListElement{
        src:"/Resrc/logo/7.png"
        account:"付款码"
    }
    ListElement{
        src:"/Resrc/logo/8.png"
        account:"余额"
    }
    ListElement{
        src:"/Resrc/logo/8.png"
        account:"余额宝"
    }
    ListElement{
        src:"/Resrc/logo/8.png"
        account:"花呗"
    }
    ListElement{
        src:"/Resrc/logo/6.png"
        account:"QQ钱包"
    }
    ListElement{
        src:"/Resrc/logo/6.png"
        account:"Q币"
    }
    ListElement{
        src:"/Resrc/logo/6.png"
        account:"点卷"
    }
}
