import QtQuick

ListModel{
    id:modelquick
    ListElement{
        quickusing:"播放/暂停"
        quickbutton:"Ctrl+P"
        globalquickbutton:"Ctrl+Alt+P"
    }
    ListElement{
        quickusing:"上一首"
        quickbutton:"Ctrl+Left"
        globalquickbutton:"Ctrl+Alt+Left"
    }
    ListElement{
        quickusing:"下一首"
        quickbutton:"Ctrl+Right"
        globalquickbutton:"Ctrl+Alt+Right"
    }
    ListElement{
        quickusing:"音量加"
        quickbutton:"Ctrl+Up"
        globalquickbutton:"Ctrl+Alt+Up"
    }
    ListElement{
        quickusing:"音量减"
        quickbutton:"Ctrl+Down"
        globalquickbutton:"Ctrl+Alt+Down"
    }
    ListElement{
        quickusing:"mini/完整模式"
        quickbutton:"Ctrl+M"
        globalquickbutton:"Ctrl+Alt+M"
    }
    ListElement{
        quickusing:"喜欢歌曲"
        quickbutton:"Ctrl+L"
        globalquickbutton:"Ctrl+Alt+L"
    }
    ListElement{
        quickusing:"打开/关闭歌词"
        quickbutton:"Ctrl+D"
        globalquickbutton:"Ctrl+Alt+D"
    }
    ListElement{
        quickusing:"翻译当前歌词"
        quickbutton:"Ctrl+T"
        globalquickbutton:"Ctrl+Alt+T"
    }
}

