import QtQuick
import QtQuick.Controls
import QtQuick.Controls.Material

ListModel{
    ListElement{
        hotid:"1"
        textcolor:"#FF3A3A"
    }
    ListElement{
        hotid:"7"
    }
    ListElement{
        hotid:"13"
    }
    ListElement{
        hotid:"2"
        textcolor:"#FE4848"
    }
    ListElement{
        hotid:"8"
    }
    ListElement{
        hotid:"14"
    }
    ListElement{
        hotid:"3"
        textcolor:"#FE4848"
    }
    ListElement{
        hotid:"9"
    }
    ListElement{
        hotid:"15"
    }
    ListElement{
        hotid:"4"
        textcolor:"#FE4848"
    }
    ListElement{
        hotid:"10"
    }
    ListElement{
        hotid:"16"
    }
    ListElement{
        hotid:"5"
        textcolor:"#FE4848"
    }
    ListElement{
        hotid:"11"
    }
    ListElement{
        hotid:"17"
    }
    ListElement{
        hotid:"6"
        textcolor:"#FE4848"
    }
    ListElement{
        hotid:"12"
    }
    ListElement{
        hotid:"18"
    }
}
